version: '2'

services:
  ctfd:
    build: .
    restart: always
    expose:
      - "8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root@db/ctfd
    volumes:
      - .data/CTFd/logs:/opt/CTFd/CTFd/logs
      - .data/CTFd/uploads:/opt/CTFd/CTFd/uploads
    depends_on:
      - db

  db:
    image: liupeng0518/mysql:5.7-arm64
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .data/mysql:/var/lib/mysql
